---
title: "Comp. Analysis"
author: "Marissa Douglas"
date: "2023-05-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Packages Here:

```{r}
library(tidyverse)
library(infer)
```


Load Raw Data Here:

```{r}
raw_data <- read.csv("Competition Experiment Sp 2023 Data - Sheet1.csv")
```

Mutate Data Here:

A data table with the sums for every minute of every day per colony (how many ants are active at that minute)
```{r}
sum_data<- raw_data %>% 
  filter(! is.na(count)) %>% 
  group_by(colony, day, minute) %>%
  mutate(sum = sum(count))
sum_data
```


A data table with the proportion for every observation (count/sum)
```{r}
proportion_data <- sum_data %>% 
  mutate(prop = count/sum)
proportion_data
```

Making a data frame that includes the mean proportion of ants at a location for each day

```{r}
mean_data <- proportion_data %>% 
  group_by(colony, location, day) %>% 
  mutate(meanInDay = mean(prop))

mean_data
```

```{r}
null_dist <- mean_data %>%
  specify(meanInDay ~ colony) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>%
  calculate("diff in means", order = c("c392", "c393"))
null_dist %>% 
  visualize()
```

```{r}
obs_mean <- mean_data %>%
  specify(meanInDay ~ colony) %>%
  calculate("diff in means", order = c("c392", "c393"))
obs_mean
```



